import Head from "next/head";
import { useEffect, useState } from "react";

import styles from "../styles/Home.module.css";

export default function Home() {
  const [billions, setBillions] = useState([]);
  useEffect(() => {
    (async () => {
      const data = await (
        await fetch(`https://billions-api.nomadcoders.workers.dev`)
      ).json();
      setBillions(data);
    })();
  }, []);

  return (
    <>
      <div>
        <Head>
          <title>갈끄니까~</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/doge.png" />
        </Head>
      </div>
      <div className={styles.header}>
        <img
          src="/gotomars.jpeg"
          className={styles.headerDoge}
          alt="we go mars 갈끄니까~"
        />
      </div>
      <div className={styles.container}>
        {billions?.map((billion) => (
          <div className={styles.billionContainer} key={billion.id}>
            <img src={billion.squareImage} alt="billion Image" />
            <h4 className={styles.billionName}>{billion.name}</h4>
            <div>
              <span className={styles.billionNetWorth}>{billion.netWorth}</span>
              <span className={styles.billionIndustries}>
                {billion.industries}
              </span>
            </div>
          </div>
        ))}
      </div>
    </>
  );
}
