import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [billions, setBillions] = useState([]);
  useEffect(() => {
    (async () => {
      const data = await (
        await fetch(`https://billions-api.nomadcoders.workers.dev`)
      ).json();
      setBillions(data);
    })();
  }, []);

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <div>{billions.id}</div>;
    </>
  );
}
